### ISSUE TITLE
What does "reset" do?

### ISSUE THREAD

**Issue by gksmyth** [Bioconductor/support.bioconductor.org#13]
If I click on TAGS, then on any tag, I get a list of tagged questions. At the top of the list is a "reset" link. Clicking on "reset" gives an unexpected result, bumping me out of TAGS altogether. It is in fact equivalent to clicking on "LATEST".

So the "reset" link seems redundant and gives an unintuitive result.

**Comment by Natay** [comment]
Users more generally get tagged questions by clicking the tags on post listing or views, not by clicking TAGS, and in that sense the "reset" link is perfectly intuitive since it drops back to an unfiltered list of posts.

In addition, clicking on tag means you are sub-selecting a list of posts so "resetting" would entail you remove the sub-selection and reset to an unfiltered list, not drop back to the previous page. 

I see where your confusion comes from, but it is unintrusive enough to keep.

**Comment by gksmyth** [comment]
With all respect Natay, I was not at all confused and you do not know how users use the website or what they will find intuitive.

Anyway, you seem to agree that the reset button is the same as clicking on LATEST, so it simply replicates the effect of another button already available on the same page. I am not clear why you feel an entirely redundant button is a good idea.

**Comment by Natay** [comment]
Not intrusive and not a bug, we'll see if admins share your opinion and change accordingly. I don't mind either way.

**Comment by gksmyth** [comment]
Did not suggest it was a "bug". As you would know, Martin and Lori have requested that all issues and concerns (not just bugs) be raised here rather than by email or slack.

**Comment by lshep** [comment]
I think I would expect the reset button on the tags to go back to the list of tags and not necessarily latest posts

**Comment by Natay** [comment]
The reset button now redirects to tags list page.
