### ISSUE TITLE
Reputations changed

### ISSUE THREAD

**Issue by gksmyth** [Bioconductor/support.bioconductor.org#26]
The user reputations changed massively today. James MacDonald and I both lost 15k or more points. Was this intentional?

The indefatible "guest-user" still rates highly however, so not all is lost.

**Comment by Natay** [comment]
Thanks for letting us know, we are looking into it. 

Just to clarify, were the scores correct when the upgrade happened yesterday and you lost points sometime today?

**Comment by gksmyth** [comment]
@Natay Yes, I think the reputation scores were correct earlier today. The scores were certainly correct in the recent past, before the upgrade went public.

**Comment by Natay** [comment]
The scores were being computed on each vote, so the new reduced scores are the actual correct ones based on the votes you received.
I updated the scores and made it so scores are incremented/decremented on each vote instead of being recomputed. 

The reputation scores are back to their unreduced form.
