### ISSUE TITLE
email notifications have encoded characters

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/support.bioconductor.org#42]
For instance, a recent email has title `ah &lt;-  AnnotationHub() Error in UseMethod(&quot;filter_&quot;): no ap…` whereas the text is `ah <- AnnotationHub()...`. This occurs in both the title and the body.

Also, I believe the email notifications had previously been in 'plain text' rather than HTML?

**Comment by guidohooiveld** [comment]
Idem for me.
To me it looks emails are 'plain text' now, rather than 'rich text' or even 'HMTL'.
Or could it be due to UTF8 (or latin) encoding?

**Comment by Natay** [comment]
Thank you for letting us know.

We changed the backend to use mass mailing, which inadvertently caused for the post content to be escaped. We will push out a fix. 

@mtmorgan , emails were in HTML before

**Comment by Natay** [comment]
This issue has been resolved

**Comment by guidohooiveld** [comment]
@Natay : could you please double-check?
I am asking because after you closed this issue I got (for example) this email (I highlighted the 'problems)':

"Thanks, @ATpoint-13662 

Yes, I realized a day after posting it and going through the vignette again. Our Null hypothesis in starting is usually that there is no change in the gene expression. If the `padj values &lt; 0.05 we` reject the null hypothesis and accept the alternate hypothesis that there is a significant change in gene expression. So to fish out genes that are not affected by treatment, maybe I need to `consider padj&gt;0.05 criteria.` Having said that, I need to confirm this: So for genes with `padj&gt;0.05`, the LFC values `doesn&#x27;t `make any sense (even if they are as small as 0.6 or s high as 22)? So criteria of using merely padj would suffice, right?"

Correctly formatted text is on the support site [here](https://support.bioconductor.org/p/p132724/#p132764).

**Comment by Natay** [comment]
This came from a different email template we overlooked, we will push out a fix for this, I will reopen the issue until then.

**Comment by Natay** [comment]
This issue has been correctly resolved.

**Comment by mtmorgan** [comment]
I received this just now...

```
User SamGG wrote Comment: read.flowSet() raises &quot; Argument &#x27;phenoData&#x27; must be of type &#x27;AnnotatedDataFrame:
```
which has two styles of encoding...

**Comment by Natay** [comment]
@mtmorgan what is the post that gives this issue?

**Comment by mtmorgan** [comment]
@Natay https://support.bioconductor.org/p/p132747/#p132788

**Comment by Natay** [comment]
A fix as been pushed out for this for a week or so, the titles are no longer being escaped.

**Comment by guidohooiveld** [comment]
FYI: i just got emails with a wrongly-formatted title from this thread:
`[bioc] Calculate Cook&#x27;s cutoff per comparison in DESeq2`
Here: https://support.bioconductor.org/p/p132945/

**Comment by Natay** [comment]
The subject needed to be marked as safe, we pushed out a fix and will keep an eye out.

**Comment by Natay** [comment]
This issue has been fixed in recent deployments.
