### ISSUE TITLE
Upper limit of 10 watched tags

### ISSUE THREAD

**Issue by kevinrue** [Bioconductor/support.bioconductor.org#91]
@lshep 

As requested, an issue acting as sticky note for looking into the upper limit of 10 watched tags.

That limit should be either removed or (more likely) simply relaxed, to allow for maintainers of 11+ packages to watched all their packages. BiocCheck throws a tantrum when maintainers don't watch tags of their package names.

Thanks!

**Comment by lshep** [comment]
@Natay  curious on this one -- I thought we had relaxed it?   Is there a secondary constraint in the database for text/character length that it is hitting rather than a strict 10 term limit?  In account forms there is a max_tags but set for 50 but if that is really what is controlling (or should control it) doesn't seem to respect it?

**Comment by kevinrue** [comment]
Oh wait. I think you've relaxed it indeed. I didn't realise that I was trying to add a tag that was already there.

That being said, the label next to the field still states that there is an upper limit of 10:

> Get email when a post matching the tag is posted. Limit of 10. Example: minia, bedops, breakdancer, music.

In summary: the limit of 10 was lifted (to what?) but the label still needs an update :)

**Comment by Natay** [comment]
@lshep correct, the max_tags in the account forms is what controls that
