### ISSUE TITLE
post tags is red and won't allow me to post a question

### ISSUE THREAD

**Issue by EmelineFavreau** [Bioconductor/support.bioconductor.org#97]
Hello,

I am trying to ask a question on the forum but it remains impossible to publish. I do not know why.
I picked tags that are available in the drop down menu. I thus do not understand why it is in red.
I replicated the error in Firefox and Chrome.

What needs to be done?

Thanks!

<img width="1229" alt="Screenshot 2023-12-14 at 11 42 21" src="https://github.com/Bioconductor/support.bioconductor.org/assets/9661216/a80a4ec8-09ee-48d1-a8b2-47f8e04a64ac">

**Comment by lshep** [comment]
Sorry we will see if we can produce more clearly why something won't post.  In this case there is not a valid Bioconductor package listed in the Post Tags section which is why it is red.  FlowCytometry is not a Bioconductor package; nor is scales.  You should ask on stackoverflow for questions about scales.  From the looks of the package landing page it looks like 1.3.0 is available from CRAN  https://cran.r-project.org/web/packages/scales/index.html   Have you tried installing scales manually?
